name: Node CI

on: 
  push:
    tags: 
      - "**"

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: echo github_ref
      shell: bash
      run: echo ${GITHUB_REF##*/}
    - name: publish
      run: |
        npm --no-git-tag-version version ${GITHUB_REF##*/}
        npm config set registry https://npm.pkg.github.com/
        npm config set authToken $NODE_AUTH_TOKEN
        npm publish
      env:
        CI: true
        NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
